### ISSUE TITLE
Fehlendes acknowledgment (ack) flag

### ISSUE THREAD

**Issue by Azathoth88** [Mic-M/iobroker-vis-view-pin-protection#1]
Seit geraumer Zeit erhalte ich die Meldung, dass der Status einen ack-flag benötigt.

<html>
<body>

javascript.0 | 2021-07-05 10:29:23.919 | warn | Read-only state "javascript.0.visViewPinSperre.Test.WrongPinEntered" has been written without ack-flag with value "false"
-- | -- | -- | --
javascript.0 | 2021-07-05 10:29:23.919 | warn | Read-only state "javascript.0.visViewPinSperre.Einstellungen.WrongPinEntered" has been written without ack-flag with value "false"
javascript.0 | 2021-07-05 10:29:20.922 | warn | Read-only state "javascript.0.visViewPinSperre.Test.PinWildcards" has been written without ack-flag with value ""
javascript.0 | 2021-07-05 10:29:20.922 | warn | Read-only state "javascript.0.visViewPinSperre.Test.CurrentKey" has been written without ack-flag with value ""
javascript.0 | 2021-07-05 10:29:20.921 | warn | Read-only state "javascript.0.visViewPinSperre.Einstellungen.PinWildcards" has been written without ack-flag with value ""
javascript.0 | 2021-07-05 10:29:20.921 | warn | Read-only state "javascript.0.visViewPinSperre.Einstellungen.CurrentKey" has been written without ack-flag with value ""

</body>
</html>

**Comment by meistermopper** [comment]
Es müssen diese Zeilen geändert werden:

129 `setState(STATE_PATH + viewName + '.PinWildcards', G_PinBufferWildcards[viewName], true);`
143 `setState(STATE_PATH + viewName + '.WrongPinEntered', true);`
156 `setState(STATE_PATH + viewName + '.CurrentKey', '', true);`
157 `setState(STATE_PATH + viewName + '.PinWildcards', '', true);`
158 `setStateDelayed(STATE_PATH + viewName + '.WrongPinEntered', false, true, 3000); // Erst nach 3 Sekunden, für VIS-Anzeige`

Schönen Gruß
Thomas
